/**All data models are defined in src/placementEngine.ts. You will use these throughout all three classes.

interface Ad {
    adId: string;
    advertiserId: string;
    timeReceived: number;   // When the ad became available
    timeout: number;        // How long the ad is available after timeReceived
    duration: number;       // How many time units the ad runs for
    baseRevenue: number;    // Revenue before multipliers/decay
    bannedLocations: string[];  // Locations where this ad cannot be shown
}

interface Area {
    areaId: string;
    location: string;
    multiplier: number;     // Revenue multiplier for this area
    totalScreens: number;
    timeWindow: number;     // Total schedulable time for this area (0 to timeWindow)
}

interface ScheduledAd {
    adId: string;
    areaId: string;
    startTime: number;      // Inclusive
    endTime: number;        // Exclusive
}

type Schedule = Record<string, ScheduledAd[]>;
// Keys are areaIds. Each ScheduledAd.areaId must match the key it appears under.
*/

import { Ad, Area, Schedule, ScheduledAd, PlacementEngine } from './placementEngine';

export class RevenueEngine {
    placementEngine: PlacementEngine;

    constructor(placementEngine: PlacementEngine) {
        this.placementEngine = placementEngine;
    }

    getAdvertiserScheduleCount(
        advertiserId: string,
        ads: Ad[],
        schedule: Schedule
    ): number {
        // Return how many scheduled ads belong to the given advertiser across the full schedule. Return 0 if the advertiser has no scheduled ads.
        let count = 0;
        for (const areaId in schedule) {
            const areaSchedule = schedule[areaId];
            for (const scheduledAd of areaSchedule) {
                const ad = ads.find(a => a.adId === scheduledAd.adId);
                if (ad && ad.advertiserId === advertiserId) {
                    count++;
                }
            }
        }
        return count;
    }

    calculateDiminishedRevenue(
        baseRevenue: number,
        advertiserScheduledCount: number,
        decayRate: number
    ): number {
        // Return the reduced revenue after applying diminishing returns. When advertiserScheduledCount is 0, treat the placement as the first (k=1), so the multiplier is 1 and the result is the full baseRevenue.
        const k = advertiserScheduledCount + 1;
        const multiplier = Math.pow(decayRate, k - 1);
        return baseRevenue * multiplier;
    }

    //Come back here If you have time, this is the most important method in the class and it will be used in the scheduler to calculate the revenue of a placement
    //I think it might be failing cme back to it
    calculatePlacementRevenue(
        ad: Ad,
        areas: Area[],
        ads: Ad[],
        schedule: Schedule,
        decayRate: number
    ): number {
        //Return the final revenue for placing one ad in one area, including the area multiplier and advertiser decay.
        const area = areas.find(a => a.areaId === schedule[ad.adId][0].areaId);
        if (!area) return 0;
        const advertiserScheduledCount = this.getAdvertiserScheduleCount(ad.advertiserId, ads, schedule);
        const diminishedRevenue = this.calculateDiminishedRevenue(ad.baseRevenue, advertiserScheduledCount, decayRate);
        return diminishedRevenue * area.multiplier;
    }

    getAdvertiserDiversity(ads: Ad[], schedule: Schedule): number {
        //Return the number of unique advertisers represented in the schedule
        //mAKE A SET TO GET UNIQUE ADVERTISERTS
        const advertisers = new Set<string>();
        for (const areaId in schedule) {
            const areaSchedule = schedule[areaId];
            for (const scheduledAd of areaSchedule) {
                const ad = ads.find(a => a.adId === scheduledAd.adId);
                if (ad) {
                    advertisers.add(ad.advertiserId);
                }
            }
        }
        return advertisers.size;
    }

    getAreaRevenue(
        area: Area,
        areasArray: Area[],
        fullSchedule: Schedule,
        ads: Ad[],
        decayRate: number
    ): number {
        //Return the total revenue generated by the given area using the areas array, the full schedule, ad list, and decay rate. Revenue must account for the area’s multiplier and advertiser decay based on the full schedule, not just the target area. Return 0 when the given area's areaId is not a key in the schedule.
        const areaSchedule = fullSchedule[area.areaId];
        if (!areaSchedule) return 0;

        let totalRevenue = 0;
        for (const scheduledAd of areaSchedule) {
            const ad = ads.find(a => a.adId === scheduledAd.adId);
            if (ad) {
                // wE CAN call the calculateplacement method here 
                const placementRevenue = this.calculatePlacementRevenue(ad, areasArray, ads, fullSchedule, decayRate);
                totalRevenue += placementRevenue;
            }
        }
        return totalRevenue;
    }
}   